server:
  port: 9966
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BingYuQHS/SpringcloudConfig/
          search-paths: respo
#          username:
#          password:
      label: master
# 指定服务注册地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9876/eureka/
